### ISSUE TITLE
Search on cEDH "where is my card played"/cardtodeck seems broken

### ISSUE THREAD

**Issue by LlamaLitany** [KonradHoeffner/cedh#5]
search on https://konradhoeffner.github.io/cedh/cardtodeck.html returns no hits with enter key

**Comment by KonradHoeffner** [comment]
Hi, I just checked it with "Null Rod" where it worked, can you first check if that works for you in case it is an issue with a specific card that is misspelled or not used in any deck? Can you give me the exact search string you used and the browser name and version?

**Comment by KonradHoeffner** [comment]
P. S.: The search is quickly programmed and does not contain any error correction code. Please check if the English card name is given exactly as on the card.

**Comment by LlamaLitany** [comment]
Hi Konrad,

Thank you for this suggestion. I was searching cards with the correct names
but no caps, and correctly capitalizing my searches resolved the problem.

While we're emailing, I also wanted to bring a possible issue with
https://konradhoeffner.github.io/cedh/staples.html to your attention. It
seems to me that this page is incorrectly tracking double-sided cards such
as Birgi, God of Storytelling, Search for Azcanta, the various Pathways,
etc. These cards show up as 0 count to me, which is easily visible if you
sort cards by count low to high. (I'm encountering this issue on Google
Chrome Version 111.0.5563.147, if that helps). My guess would be that the
error comes from some disconnect between the names recorded in
https://konradhoeffner.github.io/cedh/data/decks.json (both sides of the
card separated by // ) and the names that the staples database recognizes
(the front side of each double-sided card).

This second issue may already be something you're aware of, but I figured
that I would bring it to your attention while I was already emailing. Thank
you for producing this remarkable resource and please let me know if
there's any more information I can provide!

Thanks,
Will

**Comment by KonradHoeffner** [comment]
Hi Will, thank you for the report and the praise! I am glad this resource is helpful to someone.
If will try to find the time to build some robustness into the search function at least regarding capitalization and maybe also typos, as this would be a simple feature to implement.

I was not aware that double sided cards show up with a count of 0 in the staples list and will create a new issue for that and close this one, thanks!

In case you didn't know, please note that replying on emails generated by GitHub will be included publicly in the issue that raised the email.
While this is perfectly fine in this case, your comment "while we are emailing" leads me to believe that may have interpreted the email generated by the GitHub issue as direct mail.
So I just wanted to make sure you don't run the risk of mixing up private/public communication in the future.
